# backend editor ajax routes
-
  name: 'H5P Backend Editor AJAX'
  uriPattern: 'neosh5p/editor'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'index'
-
  name: 'H5P Backend Editor AJAX - content type cache'
  uriPattern: 'neosh5p/editor/content-type-cache'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'contentTypeCache'
-
  name: 'H5P Backend Editor AJAX - library install'
  uriPattern: 'neosh5p/editor/library-install{queryString}'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'installLibrary'
-
  name: 'H5P Backend Editor AJAX - single library details'
  uriPattern: 'neosh5p/editor/libraries{queryString}'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'libraryDetails'
  httpMethods: ['GET']
-
  name: 'H5P Backend Editor AJAX - multiple libraries'
  uriPattern: 'neosh5p/editor/libraries'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'libraries'
  httpMethods: ['POST']
-
  name: 'H5P Backend Editor AJAX - editor file upload'
  uriPattern: 'neosh5p/editor/files'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'fileUpload'
  httpMethods: ['POST']

# backend content upgrade ajax routes
-
  name: 'H5P Backend content upgrade AJAX - execute content upgrade'
  uriPattern: 'neosh5p/contentupgrade/migrate/{oldLibraryId}'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\ContentUpgradeAjax'
    '@action': 'migrateContent'
  httpMethods: ['POST']
-
  name: 'H5P Backend content upgrade AJAX - get library info'
  uriPattern: 'neosh5p/contentupgrade/libraryinfo(/{libraryName}/{majorVersion}/{minorVersion})'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\ContentUpgradeAjax'
    '@action': 'libraryInfo'
    'libraryName': ''
    'majorVersion': '0'
    'minorVersion': '0'
  httpMethods: ['POST']

# frontend ajax routes
-
  name: 'H5P Frontend AJAX - save results'
  uriPattern: 'neosh5p/contentresults/save'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Frontend\ContentResults'
    '@action': 'save'
  httpMethods: ['POST']
-
  name: 'H5P Frontend AJAX - save content user data'
  uriPattern: 'neosh5p/contentuserdata/save/{queryString}'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Frontend\ContentUserData'
    '@action': 'save'
    'queryString': 'contentId=:contentId&dataType=:dataType&subContentId=:subContentId'
  httpMethods: ['POST']

# embed route for content
-
  name: 'H5P Frontend - embed content as iframe'
  uriPattern: 'neosh5p/content/embed/{contentId}'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Frontend\ContentEmbed'
    '@action': 'index'
